modLoader = "javafml"
loaderVersion = "[4,)"
license = "MIT"

[[mods]]
modId = "armor_addon"
version = "${version}"
displayName = "盔甲附加 (Armor Addon)"
description = '''添加了一些额外的盔甲'''

[[dependencies.armor_addon]]
modId = "neoforge"
type = "required"
versionRange = "[21.1.244,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.armor_addon]]
modId = "minecraft"
type = "required"
versionRange = "[1.21.1]"
ordering = "NONE"
side = "BOTH"
